name: plugin_devkit
publish_to: none
resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  matcher: ^0.12.17
  plugin_contracts:
    path: ../plugin_contracts
  plugin_runtime:
    path: ../plugin_runtime
  plugin_flutter:
    path: ../plugin_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
