name: plugin_flutter
publish_to: none
resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  plugin_contracts:
    path: ../plugin_contracts

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
